services:
    laravel:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '9000:9000'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

    webserver:
        image: nginx:latest
        restart: always
        ports:
            - 9999:80
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf #works
            - ./public:/usr/share/nginx/html
        depends_on:
            -   laravel
        networks:
            - sail

    heartbeat:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always


networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
