services:

    nginx:
        build:
            context: "./docker/nginx"
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            #            port mappings, host to docker
            - "4443:443"
            - "9999:80"
        restart: always
        depends_on:
            -   php-fpm
            -  mysql
        networks:
            - sail

    php-fpm:
        build:
            context: "./docker/php-fpm"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        restart: always
        depends_on:
            -   mysql
        expose:
            - "9000"
        networks:
            - sail


    mysql:
        image: 'container-registry.oracle.com/mysql/community-server:8.4'
        ports:
            - '3307:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail


    heartbeat:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always


    consumer:
        build:
            context: docker/consumer
            dockerfile: Dockerfile
        restart: always
        networks: 
            - my_shared_network
           

networks:
    sail:
        driver: bridge
    my_shared_network:
        external: true
volumes:
    sail-mysql:
        driver: local




