version: "3.8"

services:

  # Database
  database:
    image: container-registry.oracle.com/mysql/community-server:8.4
    environment: # Variables defined in .env
      MYSQL_DATABASE: Hackathon_Desiderius
      MYSQL_ROOT_PASSWORD: password
    restart: always # Check need
    ports: # Check need + port (if changed => also change in .env file)
      - 3307:3306
    volumes:
      - frontend-db-data:/var/lib/mysql
    networks:
      - laravel_backend

  # Apache Service
  webserver:
    image: nginx:latest
    restart: always
    ports:
      - 9999:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf #works
      - ./public:/usr/share/nginx/html
    networks:
      - laravel_backend

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - database
    networks:
      - laravel_backend

  #PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=base64:gNiYlzaan1JfJKdnwWqYb6VbLPPWSMkBb82cE9u7cwM=
      - CONTAINER_ROLE=app
    working_dir: /var/www
    restart: always
    command: >
      bash -c "chown -R www-data:www-data /var/www/storage &&
               chown -R www-data:www-data /var/www/bootstrap/cache &&
               chown -R www-data:www-data /var/www/public &&
               chmod -R 775 /var/www/storage &&
               chmod -R 775 /var/www/public &&
               php-fpm -F"
    volumes:
      - ./:/var/www
    ports:
      - 8000:9000
    expose:
      - 9000
    depends_on:
      - database
    networks:
      - laravel_backend

  # Heartbeat Service
  heartbeat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

volumes:
  frontend-db-data:

networks:
  laravel_backend:
    driver: bridge
