services:

    nginx:
        build:
            context: "./docker/nginx"
        depends_on:
            - php-fpm
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            #            port mappings, host to docker
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        restart: always
        networks:
            - sail

    php-fpm:
        build:
            context: "./docker/php-fpm"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        restart: always
        networks:
            - sail
        expose:
            - "9000"


#    laravel:
#        build:
#            context: ./docker/8.3
#            dockerfile: Dockerfile
#            args:
#                WWWGROUP: '${WWWGROUP}'
#        image: sail-8.3/app
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
#        ports:
#            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
#            - '9000:9000'
#        environment:
#            WWWUSER: '${WWWUSER}'
#            LARAVEL_SAIL: 1
#            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
#            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
#            IGNITION_LOCAL_SITES_PATH: '${PWD}'
#        volumes:
#            - '.:/var/www/html'
#        networks:
#            - sail
#
#    webserver:
#        image: nginx:latest
#        restart: always
#        ports:
#            - 9999:9000
#        volumes:
#            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf #works
#            - ./public:/usr/share/nginx/html
#        depends_on:
#            -   laravel
#        networks:
#            - sail

    heartbeat:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always


networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
